/****** Object:  Table [dbo].[atm_msjenisalat]    Script Date: 05/12/2023 18:25:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[atm_msjenisalat](
	[jen_id] [int] IDENTITY(1,1) NOT NULL,
	[jen_nama] [varchar](255) NOT NULL
	
 CONSTRAINT [PK_msgolongan] PRIMARY KEY CLUSTERED 
(
	[jen_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[atm_msalat]    Script Date: 05/12/2023 18:25:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[atm_msalat](
	[ala_id] [int] IDENTITY(1,1) NOT NULL,
	[jen_id] [int] NOT NULL,
	[jen_nama] [varchar](255) NOT NULL
	
 CONSTRAINT [PK_msgolongan] PRIMARY KEY CLUSTERED 
(
	[jen_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO